# Predicting Prostate Cancer
Author: Andrew Pierson

In [1]:
#Determine the current working directory and import tools
import os
import pandas as pd
import numpy as np
import sklearn as skl
os.getcwd()

'C:\\Users\\Andrew\\Desktop\\Rockhurst University\\SS18\\BIA 6303 Predictive Models\\Homework\\Assignment #1'

In [2]:
#Change working directory to Week 3 Data folder and check to ensure changes
os.chdir('C:\\Users\\Andrew\\Desktop\\Rockhurst University\\SS18\\BIA 6303 Predictive Models\\Week 2\\data')
os.getcwd()

'C:\\Users\\Andrew\\Desktop\\Rockhurst University\\SS18\\BIA 6303 Predictive Models\\Week 2\\data'

## Exploratory Data Analysis (EDA)

In [3]:
#Import the prostate dataset, name the dataframe Prostate, and examine head portion of data
Prostate = pd.read_csv('prostate.csv')
Prostate.head()

Obs    lcavol   lweight  age      lbph  svi       lcp  gleason  pgg45  \
0    1 -0.579818  2.769459   50 -1.386294    0 -1.386294        6      0   
1    2 -0.994252  3.319626   58 -1.386294    0 -1.386294        6      0   
2    3 -0.510826  2.691243   74 -1.386294    0 -1.386294        7     20   
3    4 -1.203973  3.282789   58 -1.386294    0 -1.386294        6      0   
4    5  0.751416  3.432373   62 -1.386294    0 -1.386294        6      0   

       lpsa  
0 -0.430783  
1 -0.162519  
2 -0.162519  
3 -0.162519  
4  0.371564

In [4]:
#Perform Exploratory Data Analysis (EDA) on Churn dataframe 
#Use the describe command to find the mean, std, max, min, count, etc.
Prostate.describe()

Obs     lcavol    lweight        age       lbph        svi  \
count  97.000000  97.000000  97.000000  97.000000  97.000000  97.000000   
mean   49.000000   1.350010   3.628943  63.865979   0.100356   0.216495   
std    28.145456   1.178625   0.428411   7.445117   1.450807   0.413995   
min     1.000000  -1.347074   2.374906  41.000000  -1.386294   0.000000   
25%    25.000000   0.512824   3.375880  60.000000  -1.386294   0.000000   
50%    49.000000   1.446919   3.623007  65.000000   0.300105   0.000000   
75%    73.000000   2.127041   3.876396  68.000000   1.558145   0.000000   
max    97.000000   3.821004   4.780383  79.000000   2.326302   1.000000   

             lcp    gleason       pgg45       lpsa  
count  97.000000  97.000000   97.000000  97.000000  
mean   -0.179366   6.752577   24.381443   2.478387  
std     1.398250   0.722134   28.204035   1.154329  
min    -1.386294   6.000000    0.000000  -0.430783  
25%    -1.386294   6.000000    0.000000   1.731656  
50%    -0.798508   7.000000   15.000000   2.591516  
75%     1.178655   7.000000   40.000000   3.056357  
max     2.904165   9.000000  100.000000   5.582932

In [5]:
#Use the is.null command to produce a count of NaN or missing values, the result is none
null_counts = Prostate.isnull().sum()
null_counts[null_counts > 0].sort_values(ascending = False)

Series([], dtype: int64)

In [6]:
#Print the columns that contain null values, yay there are none! This will provide a more accurate analysis because we don't have to change the null values to an arbitrary number
null_data = Prostate[Prostate.isnull().any(axis=1)]
null_data

Empty DataFrame
Columns: [Obs, lcavol, lweight, age, lbph, svi, lcp, gleason, pgg45, lpsa]
Index: []

In [7]:
#Use the info command to explore Churn factor data types, int64 data types are preferred and object data types might be difficult to work with
Prostate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97 entries, 0 to 96
Data columns (total 10 columns):
Obs        97 non-null int64
lcavol     97 non-null float64
lweight    97 non-null float64
age        97 non-null int64
lbph       97 non-null float64
svi        97 non-null int64
lcp        97 non-null float64
gleason    97 non-null int64
pgg45      97 non-null int64
lpsa       97 non-null float64
dtypes: float64(5), int64(5)
memory usage: 7.7 KB


## Create Train and Test Datasets

In [8]:
#Create samples of the Prostate dataset using a 70%-30% split on train-test
from sklearn.model_selection import train_test_split
Prostate_train, Prostate_test = train_test_split(Prostate, test_size=0.3)

## Ridge Regression Model

In [9]:
#Construct a Ridge Regression model using the RidgeCV command, with built-in cross-validation of the alpha parameter
from sklearn import linear_model
X = Prostate_train
Y = Prostate_train['lpsa']
reg = linear_model.RidgeCV(alphas=[0.1, 1.0, 10.0])
reg.fit(X, Y)  

RidgeCV(alphas=[0.1, 1.0, 10.0], cv=None, fit_intercept=True, gcv_mode=None,
    normalize=False, scoring=None, store_cv_values=False)

In [10]:
#Print the coefficients of the RidgeCV model
reg.coef_

array([ 6.17264259e-04,  2.05693470e-03,  9.25840053e-04, -9.02513086e-05,
        3.39995018e-04,  1.09720701e-03,  5.17892853e-04,  7.08850193e-04,
       -6.38404737e-05,  9.82714553e-01])

In [11]:
#Cross validate the Ridge Regression model
reg.alpha_

0.1

In [12]:
#Run the RidgeCV model on the Prostate_test data set
reg_pred = reg.predict(Prostate_test)
reg_pred

array([ 1.76391096,  1.55275697,  2.78857848,  1.84193476,  1.9217214 ,
        2.58997276,  2.96265724,  2.3758732 ,  1.25988101,  2.67778984,
        3.01759704, -0.41421172,  2.80466252,  2.88580036,  3.56976869,
        2.27543208,  5.45624497,  1.63547833,  2.84197867,  3.63713034,
        2.97878329,  3.98630429,  1.79243514,  2.32597095,  3.43955307,
        1.68903206,  1.34521842,  1.04385772,  0.85669531,  3.46046407])

In [13]:
#Calculate the Mean Squared Error (MSE) of the Ridge Regression model
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(Prostate_test['lpsa'], reg_pred)
MSE

3.88070872859375e-05

In [14]:
#Compute the R^2 (coefficient of determination) regression score function
from sklearn import metrics
R2 = metrics.r2_score(Prostate_test['lpsa'], reg_pred)
R2

0.9999682240836654

In [15]:
#Compute the Mean Absolute Error (MAE) regression loss coefficient
MAE = metrics.mean_absolute_error(Prostate_test['lpsa'], reg_pred)
MAE

0.004317552837084578

## LASSO Regression Model

In [16]:
#Construct a LASSO model, a linear program that estimates sparse coefficients
from sklearn import linear_model
reg = linear_model.Lasso(alpha = 0.1)
reg.fit(X, Y)
reg_pred = reg.predict(Prostate_test)

In [17]:
#Run the LASSO model on the Prostate_test data set
reg_pred = reg.predict(Prostate_test)
reg_pred

array([1.60348701, 1.33093797, 2.83112053, 1.59996041, 1.80197127,
       2.55816189, 3.29627155, 2.31093602, 1.04598387, 2.63971999,
       3.28471263, 0.52572087, 2.8798008 , 3.14147198, 3.81430549,
       2.15657279, 4.35060645, 1.40868458, 2.98724783, 3.88752904,
       3.32647932, 4.02276941, 1.53718413, 2.2792797 , 3.64833248,
       1.48748817, 1.11817072, 0.92147565, 0.86994587, 3.59738553])

In [18]:
#Print the coefficients of the LASSO model
reg.coef_

array([ 0.03758995,  0.        ,  0.        , -0.00014488,  0.        ,
        0.        ,  0.        ,  0.        , -0.00152113,  0.06400137])

In [19]:
#Calculate the Mean Squared Error (MSE) of the LASSO model
from sklearn.metrics import mean_squared_error
MSE = mean_squared_error(Prostate_test['lpsa'], reg_pred)
MSE

0.10820380751927641

In [20]:
#Compute the R^2 (coefficient of determination) regression score function for the LASSO model
from sklearn import metrics
R2 = metrics.r2_score(Prostate_test['lpsa'], reg_pred)
R2

0.9114008451734095

In [21]:
#Compute the Mean Absolute Error (MAE) regression loss coefficient for the LASSO model
MAE = metrics.mean_absolute_error(Prostate_test['lpsa'], reg_pred)
MAE

0.22726197319780334

## Elastic Net Regression Model

In [22]:
#Build an ELASTIC NET model, a linear regression model trained with L1 and L2 prior as regulizer
from sklearn.linear_model import ElasticNetCV
regr = ElasticNetCV(cv = 5, random_state = 0)
regr.fit(X, Y)
regr_pred = regr.predict(Prostate_test)

In [23]:
#Compute the ELASTIC NET coefficients, alpha value, Mean Squared Error (MSE), Mean Absolute Error (MAE), and R^2 regression score
print(regr.coef_)
print(regr.alpha_)
MSE = mean_squared_error(Prostate_test['lpsa'], reg_pred)
print(MSE)
MAE = metrics.mean_absolute_error(Prostate_test['lpsa'], reg_pred)
print(MAE)
R2 = metrics.r2_score(Prostate_test['lpsa'], reg_pred)
print(R2)

[ 0.01880112  0.01629194  0.         -0.00060278  0.          0.
  0.00858144  0.         -0.0010304   0.51837492]
0.06337701743127644
0.10820380751927641
0.22726197319780334
0.9114008451734095


## Stochastic Gradient Descent (SGD) Model

In [26]:
#Construct a STOCHASTIC GRADIENT DESCENT (SGD) model, regulizer penalty added to the loss function that shrinks model parameters
clf = linear_model.SGDRegressor()
clf.fit(X, Y)
clf_pred = clf.predict(Prostate_test)
clf_pred

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDRegressor'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


array([2.31452257e+13, 1.47646109e+13, 2.61726815e+13, 2.56729118e+13,
       2.37141135e+13, 2.98251701e+13, 3.43844646e+13, 2.62841574e+13,
       1.82859298e+13, 2.88900384e+13, 3.43630688e+13, 1.22613627e+13,
       3.25908988e+13, 3.22019973e+13, 4.08274326e+13, 2.40005152e+13,
       4.33299018e+13, 1.96630975e+13, 3.33524308e+13, 3.92497073e+13,
       3.55760909e+13, 4.02640491e+13, 2.43795992e+13, 2.60906719e+13,
       3.92250881e+13, 2.01481704e+13, 1.99245105e+13, 1.36307700e+13,
       1.60843852e+13, 3.88980349e+13])

In [28]:
#Compute the STOCHASTIC GRADIENT DESCENT coefficients, Mean Squared Error (MSE), Mean Absolute Error (MAE), and R^2 regression score
print(clf.coef_)
MSE = mean_squared_error(Prostate_test['lpsa'], clf_pred)
print(MSE)
MAE = metrics.mean_absolute_error(Prostate_test['lpsa'], clf_pred)
print(MAE)
R2 = metrics.r2_score(Prostate_test['lpsa'], clf_pred)
print(R2)

[ 2.56142554e+11  2.06305344e+10 -9.11623042e+08  2.41575002e+11
  9.78580966e+09  3.97214552e+10  2.74997854e+10  1.52939783e+09
  2.45778170e+10  3.36594676e+10]
8.547716088003126e+26
27906702893284.9
-6.999018227337439e+26
